baseURL = "https://leeminhquang.github.io/blogcanhan/"
title = "Lê Minh Quang"
theme = "zzo"

defaultContentLanguage = "vi"
summaryLength = 70
buildFuture = true
copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true

[pagination]
  pagerSize = 10

[params]
  rssLimit = 100   # số không âm (0,10,20,... đều được)

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
