name: Deploy Hugo site to GitHub Pages
on:
  push:
<<<<<<< Updated upstream
    branches: [ master ]   # nếu nhánh chính là master; đổi thành main nếu bạn dùng main
=======
    branches: [ master ]
   # đổi sang nhánh chính bạn đang dùng
>>>>>>> Stashed changes
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.152.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
